using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Test.Arrays_Stings
{
    class look_and_say_sequence
    {
        /*
         * Find the n’th term in Look-and-say (Or Count and Say) Sequence. The look-and-say sequence is the sequence of below integers:
            1, 11, 21, 1211, 111221, 312211, 13112221, 1113213211, …
            How is above sequence generated?
            n’th term in generated by reading (n-1)’th term.

            The first term is "1"

            Second term is "11", generated by reading first term as "One 1" 
            (There is one 1 in previous term)

            Third term is "21", generated by reading second term as "Two 1"

            Fourth term is "1211", generated by reading third term as "One 2 One 1" 

            and so on
         */
        public look_and_say_sequence()
        {
            gen_sequence(4);
        }

        void gen_sequence(int n)
        {
            if (n == 1)
                Console.WriteLine(1);
            if (n == 2)
                Console.WriteLine(11);

            string str = "11";

            for(int i=3;i<=n;i++)
            {

                string temp = "";
                str += "$";
                int cnt = 1;

                for(int j=1;j<str.Length;j++)
                {
                    if (str[j] == str[j - 1])
                        cnt++;
                    else
                    {
                        temp += cnt;
                        temp += str[j - 1];
                    }
                }

                str = temp;
            }

            Console.WriteLine(str);
        }
    }
}
